#image: golang:1.9.4

before_script:
  # only work in intranet gitlab
  - export GOPATH="/home/gitlab-runner/builds/b7ec99ca/0/VNT"
  - export GOBIN="$GOPATH/bin"
  - export GOROOT="/usr/lib/go-1.10"
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/lib/go-1.10/bin/:$GOBIN
  - export GO_PROJECT_NAMESPACE="$GOPATH/src/github.com/vntchain"
  - export VNTCHAIN_PROJECT_DIR="$GO_PROJECT_NAMESPACE"
  - export VNT_PROJECT_DIR="$VNTCHAIN_PROJECT_DIR/go-vnt"
  - echo "Go namespace:" $GO_PROJECT_NAMESPACE
  - echo "Delete old namespace dir"
  - rm -rf $GO_PROJECT_NAMESPACE
  - mkdir -p $GO_PROJECT_NAMESPACE
  - echo "current dir:" $(pwd)
  - ln -sf $(pwd) $VNT_PROJECT_DIR
  # check go env
  - go env



stages:
  - build_test

build_and_test_job:
  stage: build_test
  script:
    - cd $VNT_PROJECT_DIR
    - echo "Build at:" $(pwd)
    - make all
    - echo "Run all tests"
    - go test ./vnt/...
    - go test ./event/...
    - go test ./params/...
    - go test ./internal/...
    - go test ./cmd/abigen
    - go test ./cmd/bootnode
    - go test ./cmd/clef
    - go test ./cmd/vntkey
    - go test ./cmd/faucet
    - go test ./cmd/gvnt
    - go test ./cmd/p2psim
    - go test ./cmd/puppeth
    - go test ./cmd/rlpdump
    - go test ./cmd/utils
    - go test ./cmd/wnode
    - go test ./log/...
    - go test ./trie/...
    - go test ./producer/...
    - go test ./tests/...
    - go test ./rlp/...
    - go test ./accounts/...
    - go test ./rpc/...
    - go test ./common/...
    - go test ./consensus/...
    - go test ./mobile/...
    - go test ./crypto/...
    - go test ./bmt/...
    - go test ./vntstats/...
    - go test ./vntclient/...
    - go test ./signer/...
    - go test ./node/...
    - go test ./metrics/...
    - go test ./whisper/...
    - go test ./les/...
    - go test ./vntdb/...
    - go test ./core/...
    - go test ./light/...
    - go test ./console/...

